/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/{workspaceID}/copilot/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List conversations
         * @description Lists the conversations of the authenticated user within the
         *     workspace, ordered by `updated_at` descending.
         */
        get: operations["listConversations"];
        put?: never;
        /**
         * Create a conversation
         * @description Creates a new chat conversation. The owner user ID and tenant ID are
         *     taken from the authenticated session, not from the request body.
         */
        post: operations["createConversation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{workspaceID}/copilot/conversations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a conversation
         * @description Retrieves a single conversation by its ID.
         */
        get: operations["getConversation"];
        put?: never;
        post?: never;
        /**
         * Delete a conversation
         * @description Permanently removes a conversation and (if configured) its messages.
         *     This operation is not reversible.
         */
        delete: operations["deleteConversation"];
        options?: never;
        head?: never;
        /**
         * Rename a conversation
         * @description Updates the title of a conversation and returns the updated entity.
         */
        patch: operations["renameConversation"];
        trace?: never;
    };
    "/{workspaceID}/copilot/conversations/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List messages of a conversation
         * @description Lists the messages of a conversation ordered by sequence (`seq`
         *     ascending). `blocks` is a free-form JSON array of UI blocks (thinking,
         *     tool call, chart, ...) and may be null.
         */
        get: operations["listMessages"];
        put?: never;
        /**
         * Append a message to a conversation
         * @description Appends a `user` or `assistant` message to a conversation and returns
         *     the persisted message including its sequence number.
         */
        post: operations["addMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{workspaceID}/copilot/task": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create an agent task
         * @description Creates a new LLM agent task from a prompt and optional conversation
         *     history. The task is executed only after the client subscribes to its
         *     SSE stream (`GET /task/{id}/stream`), so no events are lost. Returns
         *     the created task (state `running` once started).
         */
        post: operations["createTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{workspaceID}/copilot/task/{id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Subscribe to a task's SSE event stream
         * @description Opens a Server-Sent-Events connection for a task and starts it.
         *     Events are JSON lines prefixed with `data: ` and separated by blank
         *     lines, with the shape:
         *     `{"type": <event>, "task_id": "...", "data": {...}}`.
         *
         *     Event types:
         *     - `task_created` / `task_started`: task lifecycle
         *     - `step` (data.type in thinking | tool_call | tool_result | approval | final):
         *       reasoning chunks, tool calls, tool results, approval steps and the
         *       final answer
         *     - `approval`: asks for human approval of a risky tool call
         *     - `done` / `failed` / `cancelled`: terminal states
         */
        get: operations["streamTask"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{workspaceID}/copilot/task/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve or reject a pending tool call
         * @description Resolves a paused task waiting for human approval. When approved, the
         *     pending tool call proceeds; when rejected, it is skipped.
         */
        post: operations["approveTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{workspaceID}/copilot/task/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a task
         * @description Retrieves the current state of a task (including its accumulated
         *     steps). Purely read-only and safe to poll; it never re-runs the task.
         */
        get: operations["getTask"];
        put?: never;
        post?: never;
        /**
         * Cancel a task
         * @description Cancels a running (or pending) task and marks it `cancelled`.
         */
        delete: operations["cancelTask"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Service health check
         * @description Returns the service health status.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service is healthy. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @example ok
                             * @enum {string}
                             */
                            status?: "ok";
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Prometheus metrics
         * @description Exposes Prometheus-format metrics for the service.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Prometheus metrics in text format. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Conversation: {
            /**
             * Format: uuid
             * @description Conversation unique identifier
             * @example 2ce83101-f2c2-4f28-8111-627e9aab0234
             */
            id?: string;
            /**
             * Format: uuid
             * @description Owner user ID (from the authenticated session)
             */
            user_id?: string;
            /**
             * Format: uuid
             * @description Tenant (workspace) ID the conversation belongs to
             */
            tenant_id?: string;
            /**
             * @description Conversation title
             * @example 统计当前租户下的设备总数
             */
            title?: string;
            /**
             * Format: date-time
             * @description Creation time
             */
            created_at?: string;
            /**
             * Format: date-time
             * @description Last update time
             */
            updated_at?: string;
        };
        ConversationsPage: {
            /**
             * @description Total number of conversations
             * @example 13
             */
            total?: number;
            conversations?: components["schemas"]["Conversation"][];
        };
        Message: {
            /**
             * Format: uuid
             * @description Message unique identifier
             */
            id?: string;
            /**
             * Format: uuid
             * @description Parent conversation ID
             */
            conversation_id?: string;
            /**
             * @description Message author role
             * @example user
             * @enum {string}
             */
            role?: "user" | "assistant";
            /** @description Message text content */
            content?: string;
            /**
             * @description Free-form JSON of UI blocks (thinking / tool call / tool result /
             *     chart / approval ...). May be null.
             */
            blocks?: Record<string, never> | null;
            /**
             * @description Sequence number inside the conversation
             * @example 1
             */
            seq?: number;
            /**
             * Format: date-time
             * @description Creation time
             */
            created_at?: string;
        };
        MessagesPage: {
            /**
             * @description Total number of messages
             * @example 4
             */
            total?: number;
            messages?: components["schemas"]["Message"][];
        };
        HistoryMessage: {
            /** @enum {string} */
            role?: "user" | "assistant";
            content?: string;
        };
        Step: {
            /**
             * @example tool_call
             * @enum {string}
             */
            type?: "thinking" | "tool_call" | "approval" | "tool_result" | "final";
            /** @description Step index */
            step?: number;
            /** @description Tool name (for tool_call / tool_result) */
            tool_name?: string;
            /** @description Tool call arguments (free-form JSON) */
            params?: Record<string, never>;
            /** @description Chunk text (thinking / final) */
            content?: string;
            /**
             * @description Risk level of a tool call
             * @example read
             * @enum {string}
             */
            risk?: "read" | "modify" | "danger";
            /** @description Approval decision (approval / tool_call) */
            approved?: boolean | null;
            /** Format: date-time */
            ts?: string;
        };
        Task: {
            /**
             * Format: uuid
             * @description Task unique identifier
             */
            id?: string;
            /**
             * Format: uuid
             * @description Owner user ID
             */
            user_id?: string;
            /**
             * Format: uuid
             * @description Tenant (workspace) ID
             */
            tenant_id?: string;
            /** @description The user prompt */
            prompt?: string;
            /** @description Whether the task streams events */
            stream?: boolean;
            history?: components["schemas"]["HistoryMessage"][];
            /**
             * @example done
             * @enum {string}
             */
            state?: "running" | "paused_approval" | "done" | "failed" | "cancelled";
            /** @description Accumulated execution steps */
            steps?: components["schemas"]["Step"][];
            /** @description Final conclusion */
            final_answer?: string;
            /** @description Failure reason (when state = failed) */
            error?: string;
            pending_approval?: components["schemas"]["Step"];
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        SSEEnvelope: {
            /**
             * @example step
             * @enum {string}
             */
            type?: "task_created" | "task_started" | "step" | "approval" | "done" | "failed" | "cancelled";
            /** Format: uuid */
            task_id?: string;
            /**
             * @description Event payload. For `step` it carries `type` (thinking / tool_call /
             *     tool_result / approval / final) plus the step fields; for `approval`
             *     it carries the pending tool call; for terminal events it is omitted.
             */
            data?: Record<string, never>;
        };
    };
    responses: {
        /** @description Conversation data. */
        ConversationRes: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Conversation"];
            };
        };
        /** @description Page of conversations. */
        ConversationsPageRes: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ConversationsPage"];
            };
        };
        /** @description Message data. */
        MessageRes: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Message"];
            };
        };
        /** @description Page of messages. */
        MessagesPageRes: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["MessagesPage"];
            };
        };
        /** @description Task data. */
        TaskRes: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Task"];
            };
        };
        /** @description Deletion result. */
        DeletedRes: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @example true */
                    deleted?: boolean;
                };
            };
        };
        /** @description Cancellation result. */
        CancelledRes: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** Format: uuid */
                    task_id?: string;
                    /** @example true */
                    cancelled?: boolean;
                };
            };
        };
        /** @description Approval result. */
        ApproveTaskRes: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** Format: uuid */
                    task_id?: string;
                    approved?: boolean;
                };
            };
        };
        /** @description Unexpected server-side error occurred. */
        ServiceError: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
    };
    parameters: {
        /**
         * @description Tenant (workspace) ID scoping the route. Provided by the front-end; the
         *     owner user and tenant are also enforced from the authenticated session.
         * @example 51248012-9d39-4eca-a32f-6e470b676b95
         */
        WorkspaceID: string;
        /** @description Conversation ID. */
        ConversationID: string;
        /** @description Task ID. */
        TaskID: string;
        /** @description Size of the subset to retrieve. */
        Limit: number;
        /** @description Number of items to skip during retrieval. */
        Offset: number;
    };
    requestBodies: {
        /** @description JSON-formatted document describing conversation creation. */
        CreateConversationRequest: {
            content: {
                "application/json": {
                    /**
                     * @description Conversation title.
                     * @example 统计当前租户下的设备总数
                     */
                    title: string;
                };
            };
        };
        /** @description JSON-formatted document describing a conversation rename. */
        RenameConversationRequest: {
            content: {
                "application/json": {
                    /**
                     * @description New conversation title.
                     * @example 新标题
                     */
                    title: string;
                };
            };
        };
        /** @description JSON-formatted document describing a message to append. */
        AddMessageRequest: {
            content: {
                "application/json": {
                    /**
                     * @description Message author role.
                     * @example user
                     * @enum {string}
                     */
                    role: "user" | "assistant";
                    /**
                     * @description Message text content.
                     * @example 统计当前租户下的设备总数
                     */
                    content: string;
                    /** @description Optional UI blocks JSON. */
                    blocks?: Record<string, never> | null;
                };
            };
        };
        /** @description JSON-formatted document describing task creation. */
        CreateTaskRequest: {
            content: {
                "application/json": {
                    /**
                     * @description The user prompt to run through the agent.
                     * @example 统计当前租户下的设备总数
                     */
                    prompt: string;
                    /** @description Optional recent conversation history for context. */
                    history?: components["schemas"]["HistoryMessage"][];
                };
            };
        };
        /** @description JSON-formatted document describing an approval decision. */
        ApproveTaskRequest: {
            content: {
                "application/json": {
                    /**
                     * Format: uuid
                     * @description ID of the task waiting for approval.
                     */
                    task_id: string;
                    /**
                     * @description Whether to approve (true) or reject (false) the pending tool call.
                     * @example true
                     */
                    approved: boolean;
                };
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listConversations: {
        parameters: {
            query?: {
                /** @description Size of the subset to retrieve. */
                limit?: components["parameters"]["Limit"];
                /** @description Number of items to skip during retrieval. */
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path: {
                /**
                 * @description Tenant (workspace) ID scoping the route. Provided by the front-end; the
                 *     owner user and tenant are also enforced from the authenticated session.
                 * @example 51248012-9d39-4eca-a32f-6e470b676b95
                 */
                workspaceID: components["parameters"]["WorkspaceID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ConversationsPageRes"];
            /** @description Missing or invalid access token provided. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            500: components["responses"]["ServiceError"];
        };
    };
    createConversation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Tenant (workspace) ID scoping the route. Provided by the front-end; the
                 *     owner user and tenant are also enforced from the authenticated session.
                 * @example 51248012-9d39-4eca-a32f-6e470b676b95
                 */
                workspaceID: components["parameters"]["WorkspaceID"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["CreateConversationRequest"];
        responses: {
            201: components["responses"]["ConversationRes"];
            /** @description Failed due to malformed JSON or missing title. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid access token provided. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid content type. */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            500: components["responses"]["ServiceError"];
        };
    };
    getConversation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Tenant (workspace) ID scoping the route. Provided by the front-end; the
                 *     owner user and tenant are also enforced from the authenticated session.
                 * @example 51248012-9d39-4eca-a32f-6e470b676b95
                 */
                workspaceID: components["parameters"]["WorkspaceID"];
                /** @description Conversation ID. */
                id: components["parameters"]["ConversationID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ConversationRes"];
            /** @description Missing or invalid access token provided. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Conversation not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            500: components["responses"]["ServiceError"];
        };
    };
    deleteConversation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Tenant (workspace) ID scoping the route. Provided by the front-end; the
                 *     owner user and tenant are also enforced from the authenticated session.
                 * @example 51248012-9d39-4eca-a32f-6e470b676b95
                 */
                workspaceID: components["parameters"]["WorkspaceID"];
                /** @description Conversation ID. */
                id: components["parameters"]["ConversationID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["DeletedRes"];
            /** @description Missing or invalid access token provided. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Conversation not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            500: components["responses"]["ServiceError"];
        };
    };
    renameConversation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Tenant (workspace) ID scoping the route. Provided by the front-end; the
                 *     owner user and tenant are also enforced from the authenticated session.
                 * @example 51248012-9d39-4eca-a32f-6e470b676b95
                 */
                workspaceID: components["parameters"]["WorkspaceID"];
                /** @description Conversation ID. */
                id: components["parameters"]["ConversationID"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["RenameConversationRequest"];
        responses: {
            200: components["responses"]["ConversationRes"];
            /** @description Failed due to malformed JSON or missing title. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid access token provided. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Conversation not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid content type. */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            500: components["responses"]["ServiceError"];
        };
    };
    listMessages: {
        parameters: {
            query?: {
                /** @description Size of the subset to retrieve. */
                limit?: components["parameters"]["Limit"];
                /** @description Number of items to skip during retrieval. */
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path: {
                /**
                 * @description Tenant (workspace) ID scoping the route. Provided by the front-end; the
                 *     owner user and tenant are also enforced from the authenticated session.
                 * @example 51248012-9d39-4eca-a32f-6e470b676b95
                 */
                workspaceID: components["parameters"]["WorkspaceID"];
                /** @description Conversation ID. */
                id: components["parameters"]["ConversationID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["MessagesPageRes"];
            /** @description Missing or invalid access token provided. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Conversation not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            500: components["responses"]["ServiceError"];
        };
    };
    addMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Tenant (workspace) ID scoping the route. Provided by the front-end; the
                 *     owner user and tenant are also enforced from the authenticated session.
                 * @example 51248012-9d39-4eca-a32f-6e470b676b95
                 */
                workspaceID: components["parameters"]["WorkspaceID"];
                /** @description Conversation ID. */
                id: components["parameters"]["ConversationID"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["AddMessageRequest"];
        responses: {
            201: components["responses"]["MessageRes"];
            /** @description Failed due to malformed JSON, missing content or invalid role. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid access token provided. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Conversation not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid content type. */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            500: components["responses"]["ServiceError"];
        };
    };
    createTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Tenant (workspace) ID scoping the route. Provided by the front-end; the
                 *     owner user and tenant are also enforced from the authenticated session.
                 * @example 51248012-9d39-4eca-a32f-6e470b676b95
                 */
                workspaceID: components["parameters"]["WorkspaceID"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["CreateTaskRequest"];
        responses: {
            201: components["responses"]["TaskRes"];
            /** @description Failed due to malformed JSON or missing prompt / bearer token. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid access token provided. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid content type. */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            500: components["responses"]["ServiceError"];
        };
    };
    streamTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Tenant (workspace) ID scoping the route. Provided by the front-end; the
                 *     owner user and tenant are also enforced from the authenticated session.
                 * @example 51248012-9d39-4eca-a32f-6e470b676b95
                 */
                workspaceID: components["parameters"]["WorkspaceID"];
                /** @description Task ID. */
                id: components["parameters"]["TaskID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description Server-Sent-Events stream of task events (text/event-stream).
             *     Terminates on terminal event or when the client closes.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["SSEEnvelope"];
                };
            };
            /** @description Missing or invalid access token provided. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Task not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Failed to start the task or streaming is not supported. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    approveTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Tenant (workspace) ID scoping the route. Provided by the front-end; the
                 *     owner user and tenant are also enforced from the authenticated session.
                 * @example 51248012-9d39-4eca-a32f-6e470b676b95
                 */
                workspaceID: components["parameters"]["WorkspaceID"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["ApproveTaskRequest"];
        responses: {
            200: components["responses"]["ApproveTaskRes"];
            /** @description Failed due to malformed JSON or missing task ID. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid access token provided. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid content type. */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            500: components["responses"]["ServiceError"];
        };
    };
    getTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Tenant (workspace) ID scoping the route. Provided by the front-end; the
                 *     owner user and tenant are also enforced from the authenticated session.
                 * @example 51248012-9d39-4eca-a32f-6e470b676b95
                 */
                workspaceID: components["parameters"]["WorkspaceID"];
                /** @description Task ID. */
                id: components["parameters"]["TaskID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["TaskRes"];
            /** @description Missing or invalid access token provided. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Task not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            500: components["responses"]["ServiceError"];
        };
    };
    cancelTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Tenant (workspace) ID scoping the route. Provided by the front-end; the
                 *     owner user and tenant are also enforced from the authenticated session.
                 * @example 51248012-9d39-4eca-a32f-6e470b676b95
                 */
                workspaceID: components["parameters"]["WorkspaceID"];
                /** @description Task ID. */
                id: components["parameters"]["TaskID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["CancelledRes"];
            /** @description Missing or invalid access token provided. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Task not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            500: components["responses"]["ServiceError"];
        };
    };
}
